### ISSUE TITLE
"@v1" syntax doesn't work because of missing Git tag

### ISSUE THREAD

**Issue by lx4r** [TimonLukas/action-static-redbean#2]
Thanks for building this GH Action! :)

I tried to use the Action with a simple configuration close to the example in the README:

```yaml
- name: Package app
  uses: TimonLukas/action-static-redbean@v1
  with:
    version: "latest"
    executable-name: "my_app.com"
    input: "build"
    fallback: false
```

My workflow failed with the error "Unable to resolve action `TimonLukas/action-static-redbean@v1`, unable to find version `v1`". Based on [this](https://github.com/FranzDiebold/github-env-vars-action/issues/18) issue I was able to fix my workflow by changing `uses: TimonLukas/action-static-redbean@v1` to `uses: TimonLukas/action-static-redbean@v1.0.2`.

I think it would be good to add `v1` as a Git tag to enable using the Action with `uses: TimonLukas/action-static-redbean@v1` :)
